### PR TITLE
Add exit(1) if programming is not successful

### PR DESCRIPTION
**Pull request by Jesus89**
This is required to detect the error in programming for APIO and Icestudio.

### CODE REVIEW

**Comment by tinyfpga** [comment]
Thanks for your work @Jesus89!  I noticed this particular `exit(1)` gets executed if the boot commandline option is not selected.  I think this might not be correct.  I don't think we should return an error return code based on whether the boot flag is passed on the command line.

Maybe I'm missing something.  Could you help me understand the intention of this particular commit?  Thanks!

**Comment by Jesus89** [comment]
Yes, of course @tinyfpga. I'll try to clarify this PR: the main behavior I want to achieve with this code is to exit with an error if the programming does not succeed because "Bootloader is not active".

So instead of this *wrong* success message:

```
$ apio upload
Board: TinyFPGA-B2
[...] Processing TinyFPGA-B2
--------------------------------------------------------------------------------
tinyfpgab -c /dev/ttyACM0 --program hardware.bin

TinyFPGA B-series Programmer CLI
--------------------------------
Using device id 1209:2100
Programming /dev/ttyACM0 with hardware.bin
Bootloader not active
Bootloader not active
Bootloader not active
========================= [ SUCCESS ] Took 8.82 seconds =========================
```

It should launch an error message like this one:

```
$ apio upload
Board: TinyFPGA-B2
[...] Processing TinyFPGA-B2
--------------------------------------------------------------------------------
tinyfpgab -c /dev/ttyACM0 --program hardware.bin

TinyFPGA B-series Programmer CLI
--------------------------------
Using device id 1209:2100
Programming /dev/ttyACM0 with hardware.bin
Bootloader not active
Bootloader not active
Bootloader not active
scons: *** [upload] Error 1
========================= [ ERROR ] Took 8.82 seconds =========================
```

In the code in the [# program the flash memory](https://github.com/tinyfpga/TinyFPGA-B-Series/blob/master/programmer/tinyfpgab/__main__.py#L64) section, the execution reaches [line 93](https://github.com/tinyfpga/TinyFPGA-B-Series/blob/master/programmer/tinyfpgab/__main__.py#L93) only if it fails all the attempts. This should be a good place to put the `sys.exit(1)`, but before that it comes the last **# boot the FPGA** section, that's why the else.

I have updated the else to include this condition: `args.program is not None`. So with these changes there will be the desired behavior, and the boot option will behave in the same way.

I hope this helps. Also, I listen for better solutions :)

Regards!

**Comment by Jesus89** [comment]
Thanks!!

PS: It would also be nice a `1.0.4` release in pypi to have these changes (and my other PR) available :smile:

**Comment by tinyfpga** [comment]
updated tinyfpgab module in pypi: https://pypi.python.org/pypi/tinyfpgab

**Comment by Jesus89** [comment]
:heart:

**Pull request merged**
