### PR TITLE
Initial migration to Python3

### PR DESCRIPTION
**Pull request by Obijuan**
This pr fixed the issue #13 

I've tested with my tinyFPGAB2 on Linux and it works with python3. I've been able to program a bitstream. Also, the tox tests are passed (with py36)

Maybe it will be a good idea to merge into a different branch so that other people can test it. Or maybe you prefer to merge it into master

### CODE REVIEW

**Comment by Obijuan** [comment]
The travis checks have failed because they were expecting a ptyhon2 program. I've checked it locally with tox, and it seems to be ok

**Comment by forensicgarlic** [comment]
it's an easy change to fix the travis expectations. At the top level there's a .travis.yml file. in the python field, change it from 2.7 to some version of 3, probably 3.6

Is the plan to only work in python 3, instead of be compatible with both however?

**Comment by Jesus89** [comment]
This should be compatible with both Python 2 and Python 3.

**Comment by tinyfpga** [comment]
Great, I was worried about Python2 support and changing to Python3 only.

I will see if I can change it so that the tests run in both 2 and 3.

**Comment by Jesus89** [comment]
I have already created a PR to the Obijuan's PR: https://github.com/Obijuan/TinyFPGA-B-Series/pull/1.

In this PR the tests are working on Python 2 and 3 ;)

**Pull request merged**
