### PR TITLE
Programmer improvements

### PR DESCRIPTION
**Pull request by Rogdham**
This pull request combines several things to improve the programmer code:
 - Unit tests to make sure the following (and future) changes do not break anything;
 - Fixing a bug in the programmer (see below);
 - Making the programmer executable with the syntax `./tinyfpgab.py` on *nix systems;
 - Making the code more pythonic (including following [PEP8](https://www.python.org/dev/peps/pep-0008/))

I suggest reviewing each commit separately.

***

In fbfee1da205f80cd05af7d2429dd81356bb6987a, I found what I believe is an error in the implementation. Please do a proper review.

The issue was occurring when the area to erase was less than 4096 bytes, did not start on a 4096 byte block, but did end on a 4096 block. In that case, the 4096 block just after was read and re-written for nothing (it was not even erased!).

### CODE REVIEW

**Comment by tinyfpga** [comment]
Just went through all the commits to get a feel for the changes.  I'm pretty happy with how they look at a first glance.  I'm going to checkout your branch and try it out and do a more in-depth review and potentially more unit tests.  Thanks for all the work you put into this!  I really appreciate it!

**Comment by Rogdham** [comment]
By the way, could you explain why, on the `write` command, you are aligning to 256 bytes?

```python
dist_to_256_byte_boundary = 256 - (current_addr & 0xff)
write_length = min(16, remaining_length, dist_to_256_byte_boundary)
```

I noticed that on the `read` command there is no such code to align on 256 bytes, so I was left wondering.

Just in case, I've added a test case specifically for that (under the `FIXME` comment).

**Comment by tinyfpga** [comment]
Writes can’t cross 256 byte boundaries while reads can.

**Comment by Rogdham** [comment]
> Writes can’t cross 256 byte boundaries while reads can.

Oh, that's why! Thanks for the explanation! I've updated the comment above the test case to reflect that.

**Review by ghost — APPROVED** [review]

**Comment by Rogdham** [comment]
Hey, I see you approved the changes, but I assume that you did not merge because of the conflict. That's not a problem, I can rebase my code on master if you want.

I'm reviewing your last commits, and I don't understand all the thing about `self.spinner` in 1242674bcef9c62a6220db2675373f0dc30c9b64, would not be enough to do a `time.sleep(0.01)` (where you put the `FIXME`) and voila? Also I don't understand how it could be “optimised away”, I mean, this is not compiled with gcc -O3, this is interpreted Python code :-)

**Comment by tinyfpga** [comment]
You are right, I haven’t merged because of the merge conflict.  It would be
helpful if you could merge the recent changes from master :)

If you use time.sleep(0.01) it will sleep for 10 milliseconds after every
16 bytes written.  Sleep causes the OS to context switch to a different
thread/process and typically will take at least a millisecond for the
thread to be active again.  You can try it out yourself....it’s too slow.
It only needs 60us or so to always avoid the race condition in the
bootloader.

The spinner variable might be able to be removed.  I was doing some
computation rather than a timed spin loop before and if I didn’t use the
result of the computation I noticed that it wouldn’t get executed and
programming would fail.

Python code gets compiled into bytecode before it’s executed.  You’ll
notice .pyc files laying around, those are the compiled bytecode files that
Python keeps to void unnecessary recompiles.

 Since I’m now using a loop that waits for a specific amount of time it
would probably be safe to remove that.  But don’t make that change for your
current pull request.

Some links you might find interesting:
http://www.aosabook.org/en/500L/a-python-interpreter-written-in-python.html

https://pypy.org/

**Comment by Rogdham** [comment]
I've just rebased on master, should be good to merge. Of course, I've added in the test code checks for the `flush()` calls as well as for `is_bootloader_active`. As before, code coverage is 100% except for the `h` function (I'm waiting for https://github.com/tinyfpga/TinyFPGA-Programmer-Application/issues/2 to remove that useless `h` function), and the `__main__` part.

For the Python code optimisation, I thought that `.pyc` files were not particullary optimised, and even the `-O` flag did not do much (cf [this stackoverflow post](https://stackoverflow.com/questions/2830358/what-are-the-implications-of-running-python-with-the-optimize-flag)).

But anyways, that's out of the scope of this pull request I believe, I just left your changes like they were, except for b4461b40b32e13c8a3edc29e1ee1e7b8734b99b6 where I make sure that they are no crash if `read_back` has not same size as `data`.

Tell me what you think!

**Pull request merged**
